repos:
- repo: local
  hooks:
  -   id: isort
      name: import sorting
      entry: isort
      language: python
  -   id: black
      name: black formatter
      entry: black
      language: python
      types: [file, python]
  -   id: ruff
      name: ruff linter
      entry: ruff check --no-fix
      language: python
      files: ^dfetch_hub/
      types: [file, python]
  -   id: pylint
      name: lint python files
      entry: pylint
      language: python
      files: ^dfetch_hub/
      types: [file, python]
  -   id: mypy
      name: type check python files
      entry: mypy
      language: python
      files: ^dfetch_hub/
      types: [file, python]
  -   id: pyright
      name: pyright type check
      entry: pyright --pythonpath .venv/bin/python
      language: python
      files: ^dfetch_hub/
      types: [file, python]
      pass_filenames: false
  -   id: bandit
      name: security linting
      entry: bandit -c pyproject.toml -r
      language: python
      files: ^dfetch_hub/
      types: [file, python]
      pass_filenames: false
      args: [dfetch_hub]
  -   id: xenon
      name: cyclomatic complexity
      entry: xenon --max-absolute C --max-modules B --max-average A
      language: python
      files: ^dfetch_hub/
      types: [file, python]
      pass_filenames: false
      args: [dfetch_hub]
  -   id: pyroma
      name: package metadata quality
      entry: pyroma --directory --min 9
      language: python
      pass_filenames: false
      args: [.]
  -   id: djlint
      name: HTML linter
      entry: djlint --lint
      language: python
      files: \.(html|jinja|j2)$
  -   id: pydocstyle
      name: docstring style
      entry: pydocstyle --convention=google
      language: python
      files: ^dfetch_hub/
      types: [file, python]
  -   id: doc8
      name: documentation style
      entry: doc8 --max-line-length 120 --extension .md
      language: python
      types_or: [rst, markdown]
