repos:
- repo: local
  hooks:
  -   id: isort
      name: import sorting
      entry: isort
      language: python
  -   id: black
      name: black formatter
      entry: black
      language: python
      types: [file, python]
  -   id: pylint
      name: lint python files
      entry: pylint
      language: python
      files: ^dfetch_hub/
      types: [file, python]
  -   id: mypy
      name: type check python files
      entry: mypy
      language: python
      files: ^dfetch_hub/
      types: [file, python]