@startuml program_components
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(user, "user", "person that uses project")

Container(input_parser, "input parser", "parses input to program project sources")
Container(project_finder, "project finder", "searches repositories for projects")
Container(project_parser, "project parser", "parses repositories data to project data")
Container(export, "export", "select data and export")
Container_Ext(dfetch, "fetch dependencies", "update project with requested dependencies")

System(project_sources, "project sources file", "contains project sources")
System(project_list, "project data list", "contains all projects for given sources")
System(output_file, "dfetch (or other format) outfile", "contains required info to get project")

Rel(user, input_parser, "add input", "url, dfetch file, ...")

Rel(input_parser, project_sources, "generates", "persist data")
Rel_R(input_parser, project_finder, "add parsed sources", "add info required to parse projects")

Rel_U(project_sources, project_finder, "add parsed sources", "add info required to parse projects")

Rel_R(project_finder, project_parser, "info to create projects")
Rel(project_parser, project_list, "generates", "persist data")

Rel_R(project_parser, export, "forward project versions")
Rel(export, output_file, "generates", "persist data")

Rel(output_file, dfetch, "let dfetch use", "dfetch manifest")

@enduml
